// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrKd4jURiAb-5KcAV3MMfVP9DeU2JhK8',
    appId: '1:126630633314:android:8156641937426592b9963b',
    messagingSenderId: '126630633314',
    projectId: 'morad-tk',
    storageBucket: 'morad-tk.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qfi-1q7huMoc0C3IMzIwKTes3GwAdTQ',
    appId: '1:126630633314:ios:fce9a2805df0df64b9963b',
    messagingSenderId: '126630633314',
    projectId: 'morad-tk',
    storageBucket: 'morad-tk.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9tedGFYOpi0O94VTKZ-238GVSeRWXCg',
    appId: '1:126630633314:web:d132de08e2afe518b9963b',
    messagingSenderId: '126630633314',
    projectId: 'morad-tk',
    authDomain: 'morad-tk.firebaseapp.com',
    storageBucket: 'morad-tk.firebasestorage.app',
    measurementId: 'G-D56BS9GHSQ',
  );
}
